services:
  app:
    build: .
    container_name: spark_localstack_airflow_trino
    ports:
      - "8080:8080"
      - "4040:4040"
      - "8083:8083"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./trino-config:/opt/trino/etc
      - ./trino-catalog:/opt/trino/etc/catalog
      - ./trino-data:/opt/trino/var
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key_here
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://minio:9000
    depends_on:
      - minio
      - hive-metastore
    networks:
      - trino-net

  hive-metastore:
    image: naushadh/hive-metastore
    container_name: hive-metastore
    environment:
      - DB_TYPE=postgres
      - DATABASE_HOST=postgres
      - DATABASE_DB=hive
      - DATABASE_USER=hive
      - DATABASE_PASSWORD=hivepassword
      - METASTORE_PORT=9083
      - INIT_SCHEMA=true
      - HIVE_METASTORE_JDBC_DRIVER=org.postgresql.Driver
      - HIVE_METASTORE_JDBC_URL=jdbc:postgresql://postgres:5432/hive?sslmode=disable
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_BUCKET=hivemetastore
      - S3_PREFIX=spark
    ports:
      - "9083:9083"
    depends_on:
      postgres:
        condition: service_healthy
      s3_setup:
        condition: service_completed_successfully
    networks:
      - trino-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9083"]
      interval: 10s
      timeout: 10s
      retries: 10

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hivepassword
      - POSTGRES_DB=hive
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - trino-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d hive"]
      interval: 5s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - trino-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5

  s3_setup:
    image: minio/minio
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 admin password && 
        mc mb -p local/hivemetastore &&
        mc policy set public local/hivemetastore
      "
    environment:
      - S3_BUCKET=hivemetastore
    networks:
      - trino-net

networks:
  trino-net:
    driver: bridge

volumes:
  postgres_data:
